
package TelaCadastro;

import Classes.Produto;
import Classes.Venda;
import Classes.Vendedor;
import TelaConsulta.ConsultaProduto;
import TelaConsulta.ConsultaVendedor;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lucas
 */
public class CadastroVenda extends javax.swing.JFrame {
    Produto objProduto = new Produto();
    Vendedor objVendedor = new Vendedor();
    int qtdProdutos = 0;
    float valorTotal = 0;
    
    /**
     * Creates new form CadastroVenda
     */
    public CadastroVenda() {
        initComponents();
        txtDescProduto.setEditable(false);
        txtValor.setEditable(false);
        txtQtdItens.setEditable(false);
        txtPrecoTotal.setEditable(false);
        txtVendedor.setEditable(false);
    }
    public void addProd(Produto obj){
        objProduto = obj;
        txtProduto.setText(String.valueOf(objProduto.getProdutoId()));
        txtDescProduto.setText(objProduto.getDescricao() + " - " +objProduto.getTamanho());
        txtValor.setText(String.valueOf(objProduto.getValorVenda()).replace(".",",")+"0"); 
        txtQtd.setText("1");
        txtQtd.requestFocus();
         
    }
    public void addVendedor(Vendedor obj){
        objVendedor = obj;
        txtVendedor.setText(String.valueOf(objVendedor.getPessoaId()));
    }
    public void updateValorTotal(){
        txtQtdItens.setText(String.valueOf(qtdProdutos));
        txtPrecoTotal.setText(String.valueOf(valorTotal).replace(".",","));
    }
    public boolean verificarCampos(){
        boolean vend = false, itens = false;
        if (txtVendedor.getText().isEmpty()) {
            vend = true;
        }
        if (txtQtdItens.getText().isEmpty()){
            itens = true;
        }
        if (txtPrecoTotal.getText().isEmpty()) {
            itens = true;
        }       
        if (vend || itens) {
             JOptionPane.showMessageDialog(null, "Preencha as informações antes de prosseguir","Aviso",JOptionPane.INFORMATION_MESSAGE);
            return false;
        }else{
            return true;
        }  
    }
    public void clear(){
        int qtdLinhas = gridVenda.getRowCount();
        DefaultTableModel gridProdutos = (DefaultTableModel)gridVenda.getModel();
        for (int i = 0; i < qtdLinhas; i++) {
            gridProdutos.removeRow(0);
        }
        txtVendedor.setText("");
        txtCPF.setText("");
        txtProduto.setText("");
        txtQtd.setText("");
        txtDescProduto.setText("");
        txtValor.setText("");
        txtQtdItens.setText("");
        txtPrecoTotal.setText("");
        qtdProdutos = 0;
        valorTotal = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        btnProduto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtQtd = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        txtDescProduto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridVenda = new javax.swing.JTable();
        btnAddProduto = new javax.swing.JButton();
        txtQtdItens = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        txtPrecoTotal = new javax.swing.JTextField();
        btnDelProduto = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txtVendedor = new javax.swing.JTextField();
        btnVendedor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Cadastro de Venda");

        jLabel2.setText("Produto:");

        txtProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProdutoKeyPressed(evt);
            }
        });

        btnProduto.setText("...");
        btnProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoActionPerformed(evt);
            }
        });

        jLabel3.setText("Quantidade:");

        txtQtd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQtdKeyPressed(evt);
            }
        });

        gridVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SEQ", "Código", "Descrição", "Quantidade", "Preço Unitário", "Preço Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gridVenda.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(gridVenda);

        btnAddProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/add.png"))); // NOI18N
        btnAddProduto.setText("Adicionar");
        btnAddProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProdutoActionPerformed(evt);
            }
        });

        jLabel4.setText("Quantidade de itens:");

        jLabel5.setText("Preço Total:");

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/save.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnDelProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/close.png"))); // NOI18N
        btnDelProduto.setText("Remover");
        btnDelProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelProdutoActionPerformed(evt);
            }
        });

        jLabel6.setText("CPF:");

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFActionPerformed(evt);
            }
        });

        jLabel7.setText("Vendedor:");

        txtVendedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtVendedorKeyPressed(evt);
            }
        });

        btnVendedor.setText("...");
        btnVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btnAddProduto)
                        .addGap(76, 76, 76)
                        .addComponent(btnDelProduto)
                        .addGap(203, 203, 203))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValor)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnProduto)
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtDescProduto))
                                .addGap(92, 92, 92))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnVendedor)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtQtdItens)
                                    .addComponent(txtPrecoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(btnSalvar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVendedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProduto)
                    .addComponent(jLabel3)
                    .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtDescProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddProduto)
                    .addComponent(btnDelProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQtdItens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPrecoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnSalvar)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        int qtdItens = Integer.parseInt(txtQtdItens.getText());
        Venda objVenda = new Venda();
        Venda objProdVenda[] = new Venda[qtdItens];
        Produto objProd[] = new Produto[qtdItens];
        if (txtCPF.getText().equals( "   .   .   -  ")) {
            objVenda.setCpf("");
        }else{
            objVenda.setCpf(txtCPF.getText());
            
        }
        if (verificarCampos()) {
            objVenda.setValor(Float.parseFloat(txtPrecoTotal.getText().replace(",", ".")));
            objVenda.setVendedorId(Integer.parseInt(txtVendedor.getText()));
            
            for (int i = 0; i < qtdItens; i++) {
                objProdVenda[i] = new Venda();
                objProdVenda[i].setQtd(Integer.parseInt(gridVenda.getValueAt(i,3).toString()));
                objProdVenda[i].setValorProduto(Float.parseFloat(gridVenda.getValueAt(i,4).toString().replace(",", ".")));
                objProdVenda[i].setProdutoId(Integer.parseInt(gridVenda.getValueAt(i,1).toString()));
                
                objProd[i] = new Produto();
                objProd[i].setProdutoId(Integer.parseInt(gridVenda.getValueAt(i,1).toString()));
                objProd[i].setEstoque(Integer.parseInt(gridVenda.getValueAt(i,3).toString()));
            }
            objVenda.setVendaId(objVenda.addVenda(objVenda));
            
            if (objVenda.getVendaId() != 0) {
                for (int i = 0; i < qtdItens; i++) {
                    objVenda.addProdVenda(objProdVenda[i], objVenda.getVendaId());
                }
                for (int i = 0; i < qtdItens; i++) {
                    objProd[i].baixarEstoque(objProd[i]);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Não foi possível realizar a venda."  ,"Aviso",JOptionPane.INFORMATION_MESSAGE);
            }
            
        }
        clear();
        btnVendedor.requestFocus();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoActionPerformed
        ConsultaProduto objConsProd = new ConsultaProduto();
        objConsProd.addVenda(this);
        objConsProd.setVisible(true);
    }//GEN-LAST:event_btnProdutoActionPerformed

    private void btnAddProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProdutoActionPerformed
        int qtd = Integer.parseInt(txtQtd.getText());
        if (objProduto.getEstoque() >= qtd) {
            qtdProdutos++;
            float valorProdutos = Float.parseFloat(txtValor.getText().replace(",", ".")) *  qtd;
            valorTotal += valorProdutos;
            DefaultTableModel gridProdutos = (DefaultTableModel)gridVenda.getModel();
            gridProdutos.addRow(new Object[]{   qtdProdutos,
                                                objProduto.getProdutoId(),
                                                objProduto.getDescricao(),
                                                qtd,
                                                String.valueOf(objProduto.getValorVenda()).replace(".",",")+"0",
                                                String.valueOf(valorProdutos).replace(".", ",")+"0"

                                                }
                                            );
            updateValorTotal();
        }else {
            JOptionPane.showMessageDialog(null, "Quantidade indisponível no estoque." +objProduto.getEstoque() ,"Aviso",JOptionPane.INFORMATION_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnAddProdutoActionPerformed

    private void txtQtdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtdKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnAddProduto.doClick();
        }
    }//GEN-LAST:event_txtQtdKeyPressed

    private void txtProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProdutoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            Produto objPesquisa = new Produto();
            objProduto = objPesquisa.searchProdutoId(txtProduto);
            if (objProduto.getEstoque() == 0) {
                 JOptionPane.showMessageDialog(null, "Código inválido, produto não encontrado.","Aviso",JOptionPane.INFORMATION_MESSAGE);
            }else{
                addProd(objProduto);
                 
            }
        }
    }//GEN-LAST:event_txtProdutoKeyPressed

    private void btnDelProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelProdutoActionPerformed
        int qtdLinhas = gridVenda.getSelectedRowCount();

        if(qtdLinhas < 1){
            JOptionPane.showMessageDialog(null, "Selecione uma linha para realizar essa operação");
        }else if (qtdLinhas == 1){
            int linhaSel = gridVenda.getSelectedRow();
            qtdProdutos--;
            float valorProdutos = Float.parseFloat(gridVenda.getValueAt(linhaSel,5).toString().replace(",","."));
            valorTotal -= valorProdutos;
            DefaultTableModel gridProdutos = (DefaultTableModel)gridVenda.getModel();
            gridProdutos.removeRow(linhaSel);
            updateValorTotal();
            
        }else {
            JOptionPane.showMessageDialog(null, "Selecione apenas uma linha para realizar essa operação","Aviso",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnDelProdutoActionPerformed

    private void txtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFActionPerformed

    private void txtVendedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVendedorKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVendedorKeyPressed

    private void btnVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendedorActionPerformed
        ConsultaVendedor objConsVend = new ConsultaVendedor();
        objConsVend.vendaVendedor(this);
        objConsVend.setVisible(true);
    }//GEN-LAST:event_btnVendedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduto;
    private javax.swing.JButton btnDelProduto;
    private javax.swing.JButton btnProduto;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVendedor;
    private javax.swing.JTable gridVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JTextField txtDescProduto;
    private javax.swing.JTextField txtPrecoTotal;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQtd;
    private javax.swing.JTextField txtQtdItens;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtVendedor;
    // End of variables declaration//GEN-END:variables
}
